# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
            node-version: '18'

      - name: install ns
        run: npm install -g nativescript

      - name: install modules
        run: npm install

      - name: accept android licenses
        run: yes | sdkmanager --licenses || true

      - name: build
        run: ns build android --release --env.production

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: platforms/android/app/build/outputs/apk/release/app-release.apk